// <auto-generated />
using System;
using Intelligence.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Intelligence.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IntelligenceDbContext))]
    [Migration("20260923133602_InitialIntelligence")]
    partial class InitialIntelligence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Intelligence.Domain.Entities.ProfileDashboardLayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccessProfileId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("SlotsStorage")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT")
                        .HasColumnName("SlotsJson");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccessProfileId")
                        .IsUnique();

                    b.ToTable("ProfileDashboardLayouts", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
