// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Sales.Infrastructure.Persistence;

#nullable disable

namespace Sales.Infrastructure.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    [Migration("20260920120000_PaymentsTef")]
    partial class PaymentsTef
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
