// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Automations.Infrastructure.Persistence;

#nullable disable

namespace Automations.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AutomationsDbContext))]
    [Migration("20260922020000_AddAutomationsRemindersSettings")]
    partial class AddAutomationsRemindersSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");
#pragma warning restore 612, 618
        }
    }
}
