// <auto-generated />
using Automations.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Automations.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AutomationsDbContext))]
    [Migration("20260922040000_AddCampaignsNps")]
    partial class AddCampaignsNps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");
#pragma warning restore 612, 618
        }
    }
}
