// <auto-generated />
using Clients.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Clients.Infrastructure.Migrations
{
    [DbContext(typeof(OfflineDbContext))]
    [Migration("20260918211000_AddOfflineStockMovements")]
    partial class AddOfflineStockMovements
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
