// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Clients.Infrastructure.Migrations;

[DbContext(typeof(global::Clients.Infrastructure.OfflineDbContext))]
[Migration("20260918170000_AddOfflineClinicalArtifacts")]
partial class AddOfflineClinicalArtifacts
{
}
