// <auto-generated />
using Clients.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Clients.Infrastructure.Migrations
{
    [DbContext(typeof(OfflineDbContext))]
    [Migration("20260920120000_OfflinePaymentsTef")]
    partial class OfflinePaymentsTef
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
