<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Application\Automations.Application.csproj" />
    <ProjectReference Include="..\..\Core\Infrastructure\Core.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Veterinary\Infrastructure\Veterinary.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Petshop\Infrastructure\Petshop.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Platform\Application\Platform.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
