// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Veterinary.Infrastructure.Persistence;

#nullable disable

namespace Veterinary.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VeterinaryDbContext))]
    [Migration("20260918190000_AddHospitalizationExecutionMap")]
    partial class AddHospitalizationExecutionMap
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");
#pragma warning restore 612, 618
        }
    }
}
