// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Veterinary.Infrastructure.Persistence;

#nullable disable

namespace Veterinary.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VeterinaryDbContext))]
    [Migration("20260918160000_AddClinicalExamsPrescriptionsAttachments")]
    partial class AddClinicalExamsPrescriptionsAttachments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder)
        {
        }
    }
}
