<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Application\Platform.Application.csproj" />
    <ProjectReference Include="..\..\Core\Infrastructure\Core.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenAC.Net.NFSe.Nacional.Web" Version="1.5.0.3" />
  </ItemGroup>

</Project>
